<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<br>Verification failure : expected [abc] but found [xyz]<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Mon_Aug_31_02_16_29_SGT_2020.jpg><img src=Mon_Aug_31_02_16_29_SGT_2020.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Basics" duration-ms="10890" started-at="2020-08-30T18:16:27Z" finished-at="2020-08-30T18:16:38Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="6500" started-at="2020-08-30T18:16:27Z" finished-at="2020-08-30T18:16:34Z">
      <class name="io.github.amazing010692.testcases.BankManagerLoginTest">
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:io.github.amazing010692.testcases.BankManagerLoginTest@37bd68c3]" name="loginAsBankManager" duration-ms="5381" started-at="2020-08-30T18:16:28Z" finished-at="2020-08-30T18:16:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login not successful]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login not successful
at org.testng.Assert.fail(Assert.java:96)
at io.github.amazing010692.testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<br>Verification failure : expected [abc] but found [xyz]<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Mon_Aug_31_02_16_29_SGT_2020.jpg><img src=Mon_Aug_31_02_16_29_SGT_2020.jpg height=200 width=200></img></a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- io.github.amazing010692.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="3844" started-at="2020-08-30T18:16:34Z" finished-at="2020-08-30T18:16:38Z">
      <class name="io.github.amazing010692.testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:io.github.amazing010692.testcases.AddCustomerTest@78a287ed]" name="setUp" is-config="true" duration-ms="20335" started-at="2020-08-30T18:16:07Z" finished-at="2020-08-30T18:16:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.github.amazing010692.testcases.AddCustomerTest@78a287ed]" name="addCustomerTest" duration-ms="2375" started-at="2020-08-30T18:16:35Z" data-provider="dp" finished-at="2020-08-30T18:16:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Janielle Joy]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Gregorio]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1700.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Customer not added successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Customer not added successfully
at org.testng.Assert.fail(Assert.java:96)
at io.github.amazing010692.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:io.github.amazing010692.testcases.AddCustomerTest@78a287ed]" name="tearDown" is-config="true" duration-ms="5537" started-at="2020-08-30T18:16:38Z" finished-at="2020-08-30T18:16:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.github.amazing010692.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
