<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Data Driven Basics" duration-ms="11507" started-at="2020-08-09T16:09:38Z" finished-at="2020-08-09T16:09:49Z">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="11507" started-at="2020-08-09T16:09:38Z" finished-at="2020-08-09T16:09:49Z">
      <class name="io.github.amazing010692.testcases.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:io.github.amazing010692.testcases.LoginTest@4b29d1d2]" name="setUp" is-config="true" duration-ms="11283" started-at="2020-08-09T16:09:26Z" finished-at="2020-08-09T16:09:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:io.github.amazing010692.testcases.LoginTest@4b29d1d2]" name="loginAsBankManager" duration-ms="11410" started-at="2020-08-09T16:09:38Z" finished-at="2020-08-09T16:09:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login not successful expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login not successful expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at io.github.amazing010692.testcases.LoginTest.loginAsBankManager(LoginTest.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:io.github.amazing010692.testcases.LoginTest@4b29d1d2]" name="tearDown" is-config="true" duration-ms="1062" started-at="2020-08-09T16:09:49Z" finished-at="2020-08-09T16:09:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.github.amazing010692.testcases.LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
